#!/bin/sh

# ver=$(grep -E 'let[ \t]+VERSION[ \t]+=[ \t]+[0-9]+' ./Sources/Version.swift | sed -E 's/let[ \t]+VERSION[ \t]+=[ \t]+([0-9]+)/\1/')
# ver=`expr $ver + 1`
# echo "Building version "$ver
# echo "let VERSION = "$ver > ./Sources/Version.swift

rm -rf .build
swift build -c release --arch arm64 --arch x86_64
sudo cp .build/apple/Products/Release/noxscli /usr/local/bin/noxs

