[package]
name = "noxs"
version = "1.2.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
argon2-kdf = "1.5.2"
chacha20poly1305 = "0.10.1"

[profile.release]
panic = 'abort'
